blueprint:
  name: Default Light Brightness
  description: Sets the lights to a set brightness when triggered by anything BUT an automation
  domain: automation
  author: Greg Dodd
  input:
    light:
      name: Light to set brightness of
      selector:
        entity:
          filter:
            domain: light
    brightness_pct:
      name: Brightness Percentage
      description: Set brightness percentage (defaults to 100)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
triggers:
  - trigger: state
    entity_id: !input light
    to: "on"
conditions:
  - condition: template
    value_template: "{{ trigger.to_state.context.parent_id is none }}"
    alias: If not in an automation
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: !input brightness_pct
    target:
      entity_id: !input light
mode: single