blueprint:
  name: Lights 100%
  description: Sets the lights brightness to 100% when triggered by anything BUT an automation
  domain: automation
  author: Greg Dodd
  input:
    light:
      name: Light to set brightness of
      selector:
        entity:
          filter:
            domain: light
triggers:
  - trigger: state
    entity_id: !input light
    to: "on"
conditions:
  - condition: template
    value_template: "{{ trigger.to_state.context.user_id is not none }}"
    alias: If not in an automation
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.tv_end
mode: single