blueprint:
  name: Unlock Front Door when someone comes home
  description: Unlocks a door when someone comes home, and then locks it again 10 minutes later if the sensor says it's closed
  domain: automation
triggers:
  - trigger: zone
    entity_id: !input device_tracker
    zone: zone.home
    event: enter
input:
  device_tracker: Device Tracker
  descrption: The device that should unlock the front door.
conditions:
  - condition: device
    device_id: 6f82607bee0689bf022b7d4b44a88c7a
    domain: lock
    entity_id: 6074640ada381b01bd5d6b9692417c7d
    type: is_locked
actions:
  - action: lock.unlock
    metadata: {}
    data: {}
    target:
      device_id: 6f82607bee0689bf022b7d4b44a88c7a
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - if:
      - condition: state
        entity_id: binary_sensor.front_door_sensor
        state: "off"
    then:
      - device_id: 6f82607bee0689bf022b7d4b44a88c7a
        domain: lock
        entity_id: 6074640ada381b01bd5d6b9692417c7d
        type: lock
mode: single