blueprint:
  name: Unlock Front Door when someone comes home
  description: Unlocks a door when someone comes home, turns some lights on, and then locks it again 5 minutes later if the sensor says it's closed
  domain: automation
  author: Greg Dodd
  input:
    device_tracker: 
      name: Person Tracker
      selector:
        entity:
          filter:
            domain: person
    lock_to_unlock:
      name: Lock to Unlock
      selector:
        entity:
          filter:
            domain: lock
    door_sensor:
      name: Door Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
    zone_to_monitor:
      name: Zone to Monitor
      selector:
        entity:
          filter:
            domain: zone
    inside_lights:
      name: Inside Lights to Turn On
      selector:
        entity:
          filter:
            domain: light
    outside_lights:
      name: Outside Lights to Turn On
      selector:
        entity:
          filter:
            domain: light

triggers:
  - trigger: zone
    entity_id: !input device_tracker
    zone: !input zone_to_monitor
    event: enter
conditions: []
actions:
  - alias: Actions to Run
    parallel:
      - sequence:
        - condition: state
          entity_id: !input lock_to_unlock
          state: locked
        - action: lock.unlock
          metadata: {}
          data: {}
          target:
            entity_id: !input lock_to_unlock
        - delay:
            hours: 0
            minutes: 5
            seconds: 0
            milliseconds: 0
        - condition: state
          entity_id: !input door_sensor
          state: "off"
        - condition: state
          entity_id: !input lock_to_unlock
          state: unlocked
        - action: lock.lock
          metadata: {}
          data: {}
          target:
            entity_id: !input lock_to_unlock
        alias: Manage Front Door Lock
      - sequence:
        - condition: or
          conditions:
            - condition: sun
              before: sunrise
            - condition: sun
              after: sunset
          alias: Night time
        - alias: Lights on
          parallel:
        - alias: Inside Lights
          sequence:
            - condition: state
              entity_id: !input inside_lights
              state: "off"
            - condition: state
              entity_id: light.landing
              state: "off"
            - action: light.turn_on
              metadata: {}
              data:
                brightness_pct: 100
              target:
                entity_id: !input inside_lights
        - alias: Outside Lights
          sequence:
            - condition: state
              entity_id: !input outside_lights
              state: "off"
            - action: light.turn_on
              metadata: {}
              data: {}
              target:
                entity_id: !input outside_lights
            - delay:
                hours: 0
                minutes: 15
                seconds: 0
                milliseconds: 0
            - action: light.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: !input outside_lights
        alias: Manage Lights

mode: single